### ISSUE TITLE
Add support for alignment of linear sequences

### ISSUE THREAD

**Issue by urbanslug** [urbanslug/graphite#1]
### Is your feature request related to a problem? Please describe
We'd like to be able to align reads to a reference and either come up with a consensus.

### Describe the solution you'd like
We'll determine the costs in the distance matrix at a as follows:
 - `i` = row/x axis 
 - `j` = column/y axis

Minimum of cost(i,j) :
 - Match: cost(i-1, j-1)
 - Mismatch: cost(i-1, j-1)+1
 - Deletion: cost(i-1, j) +1
 - Insertion: cost(i j-1)+1

Alignment construction is as follows:
TODO

### Describe alternatives you've considered
Use the [racket C API](https://docs.racket-lang.org/inside/index.html) and  make use of a library that already implements it.

### Additional context
This allows us to build on this information when implementing a Partial Order Alignment

---

### Implementation plan
 - [x] Generate a distance matrix
 - [x] Backtrack on the distance matrix
 - [x] Construct the optimal alignment
